/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; fill-column: 100 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */


module com { module sun { module star { module xml { module crypto {

/**
 * Interface of XML security context info
 *
 * <p>This interface XXXXXX</p>  // TODO
 */
interface XXMLSecurityContextInfo : com::sun::star::uno::XInterface
{
    /**
     * TODO
     */
    long getImplNo( ) ;

} ;

} ; } ; } ; } ; } ;


/* vim:set shiftwidth=4 softtabstop=4 expandtab cinoptions=b1,g0,N-s cinkeys+=0=break: */
